/*
 * API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = TestIT.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = TestIT.ApiClient.Client.OpenAPIDateConverter;

namespace TestIT.ApiClient.Model
{
    /// <summary>
    /// AutoTestWorkItemIdentifierApiResult
    /// </summary>
    [DataContract(Name = "AutoTestWorkItemIdentifierApiResult")]
    public partial class AutoTestWorkItemIdentifierApiResult : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AutoTestWorkItemIdentifierApiResult" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AutoTestWorkItemIdentifierApiResult() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AutoTestWorkItemIdentifierApiResult" /> class.
        /// </summary>
        /// <param name="id">WorkItem unique internal identifier (required).</param>
        /// <param name="globalId">WorkItem Global unique identifier (required).</param>
        public AutoTestWorkItemIdentifierApiResult(Guid id = default, long globalId = default)
        {
            this.Id = id;
            this.GlobalId = globalId;
        }

        /// <summary>
        /// WorkItem unique internal identifier
        /// </summary>
        /// <value>WorkItem unique internal identifier</value>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public Guid Id { get; set; }

        /// <summary>
        /// WorkItem Global unique identifier
        /// </summary>
        /// <value>WorkItem Global unique identifier</value>
        [DataMember(Name = "globalId", IsRequired = true, EmitDefaultValue = true)]
        public long GlobalId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AutoTestWorkItemIdentifierApiResult {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  GlobalId: ").Append(GlobalId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
