/*
 * API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = TestIT.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = TestIT.ApiClient.Client.OpenAPIDateConverter;

namespace TestIT.ApiClient.Model
{
    /// <summary>
    /// ConfigurationByParametersModel
    /// </summary>
    [DataContract(Name = "ConfigurationByParametersModel")]
    public partial class ConfigurationByParametersModel : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ConfigurationByParametersModel" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ConfigurationByParametersModel() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ConfigurationByParametersModel" /> class.
        /// </summary>
        /// <param name="projectId">This property is used to link configuration with project (required).</param>
        /// <param name="parameterIds">parameterIds (required).</param>
        public ConfigurationByParametersModel(Guid projectId = default, List<Guid> parameterIds = default)
        {
            this.ProjectId = projectId;
            // to ensure "parameterIds" is required (not null)
            if (parameterIds == null)
            {
                throw new ArgumentNullException("parameterIds is a required property for ConfigurationByParametersModel and cannot be null");
            }
            this.ParameterIds = parameterIds;
        }

        /// <summary>
        /// This property is used to link configuration with project
        /// </summary>
        /// <value>This property is used to link configuration with project</value>
        /*
        <example>a58827bc-4fbb-4b8d-8ddc-bfaa97dbd0d5</example>
        */
        [DataMember(Name = "projectId", IsRequired = true, EmitDefaultValue = true)]
        public Guid ProjectId { get; set; }

        /// <summary>
        /// Gets or Sets ParameterIds
        /// </summary>
        [DataMember(Name = "parameterIds", IsRequired = true, EmitDefaultValue = true)]
        public List<Guid> ParameterIds { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ConfigurationByParametersModel {\n");
            sb.Append("  ProjectId: ").Append(ProjectId).Append("\n");
            sb.Append("  ParameterIds: ").Append(ParameterIds).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
