/*
 * API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = TestIT.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = TestIT.ApiClient.Client.OpenAPIDateConverter;

namespace TestIT.ApiClient.Model
{
    /// <summary>
    /// ConfigurationParameterValueApiResult
    /// </summary>
    [DataContract(Name = "ConfigurationParameterValueApiResult")]
    public partial class ConfigurationParameterValueApiResult : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ConfigurationParameterValueApiResult" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ConfigurationParameterValueApiResult() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ConfigurationParameterValueApiResult" /> class.
        /// </summary>
        /// <param name="id">Identifier of the configuration parameter value (required).</param>
        /// <param name="value">Value of the configuration parameter (required).</param>
        public ConfigurationParameterValueApiResult(Guid id = default, string value = default)
        {
            this.Id = id;
            // to ensure "value" is required (not null)
            if (value == null)
            {
                throw new ArgumentNullException("value is a required property for ConfigurationParameterValueApiResult and cannot be null");
            }
            this.Value = value;
        }

        /// <summary>
        /// Identifier of the configuration parameter value
        /// </summary>
        /// <value>Identifier of the configuration parameter value</value>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public Guid Id { get; set; }

        /// <summary>
        /// Value of the configuration parameter
        /// </summary>
        /// <value>Value of the configuration parameter</value>
        [DataMember(Name = "value", IsRequired = true, EmitDefaultValue = true)]
        public string Value { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ConfigurationParameterValueApiResult {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
