/*
 * API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = TestIT.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = TestIT.ApiClient.Client.OpenAPIDateConverter;

namespace TestIT.ApiClient.Model
{
    /// <summary>
    /// ConfigurationParameterPreviewApiResult
    /// </summary>
    [DataContract(Name = "ConfigurationParameterPreviewApiResult")]
    public partial class ConfigurationParameterPreviewApiResult : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ConfigurationParameterPreviewApiResult" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ConfigurationParameterPreviewApiResult() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ConfigurationParameterPreviewApiResult" /> class.
        /// </summary>
        /// <param name="id">Identifier of the configuration parameter (required).</param>
        /// <param name="name">Name of the configuration parameter (required).</param>
        /// <param name="isDeleted">Is configuration parameter deleted? (required).</param>
        /// <param name="createdDate">Date of configuration parameter creation (required).</param>
        /// <param name="createdById">Identifier of user who created configuration parameter (required).</param>
        /// <param name="modifiedDate">Date of configuration parameter modification (required).</param>
        /// <param name="modifiedById">Identifier of user who modified configuration parameter (required).</param>
        /// <param name="values">Preview of configuration parameter values (required).</param>
        /// <param name="projects">Preview of assigned projects (required).</param>
        public ConfigurationParameterPreviewApiResult(Guid id = default, string name = default, bool isDeleted = default, DateTime createdDate = default, Guid createdById = default, DateTime modifiedDate = default, Guid modifiedById = default, ConfigurationParameterValueApiResultApiCollectionPreview values = default, ProjectNameApiResultApiCollectionPreview projects = default)
        {
            this.Id = id;
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for ConfigurationParameterPreviewApiResult and cannot be null");
            }
            this.Name = name;
            this.IsDeleted = isDeleted;
            this.CreatedDate = createdDate;
            this.CreatedById = createdById;
            this.ModifiedDate = modifiedDate;
            this.ModifiedById = modifiedById;
            // to ensure "values" is required (not null)
            if (values == null)
            {
                throw new ArgumentNullException("values is a required property for ConfigurationParameterPreviewApiResult and cannot be null");
            }
            this.Values = values;
            // to ensure "projects" is required (not null)
            if (projects == null)
            {
                throw new ArgumentNullException("projects is a required property for ConfigurationParameterPreviewApiResult and cannot be null");
            }
            this.Projects = projects;
        }

        /// <summary>
        /// Identifier of the configuration parameter
        /// </summary>
        /// <value>Identifier of the configuration parameter</value>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public Guid Id { get; set; }

        /// <summary>
        /// Name of the configuration parameter
        /// </summary>
        /// <value>Name of the configuration parameter</value>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Is configuration parameter deleted?
        /// </summary>
        /// <value>Is configuration parameter deleted?</value>
        [DataMember(Name = "isDeleted", IsRequired = true, EmitDefaultValue = true)]
        public bool IsDeleted { get; set; }

        /// <summary>
        /// Date of configuration parameter creation
        /// </summary>
        /// <value>Date of configuration parameter creation</value>
        [DataMember(Name = "createdDate", IsRequired = true, EmitDefaultValue = true)]
        public DateTime CreatedDate { get; set; }

        /// <summary>
        /// Identifier of user who created configuration parameter
        /// </summary>
        /// <value>Identifier of user who created configuration parameter</value>
        [DataMember(Name = "createdById", IsRequired = true, EmitDefaultValue = true)]
        public Guid CreatedById { get; set; }

        /// <summary>
        /// Date of configuration parameter modification
        /// </summary>
        /// <value>Date of configuration parameter modification</value>
        [DataMember(Name = "modifiedDate", IsRequired = true, EmitDefaultValue = true)]
        public DateTime ModifiedDate { get; set; }

        /// <summary>
        /// Identifier of user who modified configuration parameter
        /// </summary>
        /// <value>Identifier of user who modified configuration parameter</value>
        [DataMember(Name = "modifiedById", IsRequired = true, EmitDefaultValue = true)]
        public Guid ModifiedById { get; set; }

        /// <summary>
        /// Preview of configuration parameter values
        /// </summary>
        /// <value>Preview of configuration parameter values</value>
        [DataMember(Name = "values", IsRequired = true, EmitDefaultValue = true)]
        public ConfigurationParameterValueApiResultApiCollectionPreview Values { get; set; }

        /// <summary>
        /// Preview of assigned projects
        /// </summary>
        /// <value>Preview of assigned projects</value>
        [DataMember(Name = "projects", IsRequired = true, EmitDefaultValue = true)]
        public ProjectNameApiResultApiCollectionPreview Projects { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ConfigurationParameterPreviewApiResult {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  IsDeleted: ").Append(IsDeleted).Append("\n");
            sb.Append("  CreatedDate: ").Append(CreatedDate).Append("\n");
            sb.Append("  CreatedById: ").Append(CreatedById).Append("\n");
            sb.Append("  ModifiedDate: ").Append(ModifiedDate).Append("\n");
            sb.Append("  ModifiedById: ").Append(ModifiedById).Append("\n");
            sb.Append("  Values: ").Append(Values).Append("\n");
            sb.Append("  Projects: ").Append(Projects).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
