/*
 * API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = TestIT.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = TestIT.ApiClient.Client.OpenAPIDateConverter;

namespace TestIT.ApiClient.Model
{
    /// <summary>
    /// CreateTestRunAndFillByAutoTestCasesApiModel
    /// </summary>
    [DataContract(Name = "CreateTestRunAndFillByAutoTestCasesApiModel")]
    public partial class CreateTestRunAndFillByAutoTestCasesApiModel : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateTestRunAndFillByAutoTestCasesApiModel" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreateTestRunAndFillByAutoTestCasesApiModel() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateTestRunAndFillByAutoTestCasesApiModel" /> class.
        /// </summary>
        /// <param name="projectId">Specifies the GUID of the project, in which a test run will be created. (required).</param>
        /// <param name="filter">Specifies the filter for selecting autotests, from which test points are created..</param>
        /// <param name="name">Specifies the name of the test run..</param>
        /// <param name="configurationIds">Specifies the configuration GUIDs, from which test points are created. You can specify several GUIDs. (required).</param>
        /// <param name="description">Specifies the test run description..</param>
        /// <param name="launchSource">Specifies the test run launch source..</param>
        /// <param name="option">Specifies the test run launch options. (required).</param>
        /// <param name="tags">Collection of tags to assign to the test run.</param>
        public CreateTestRunAndFillByAutoTestCasesApiModel(Guid projectId = default, CompositeFilter filter = default, string name = default, List<Guid> configurationIds = default, string description = default, string launchSource = default, TestRunLaunchOptionApiModel option = default, List<string> tags = default)
        {
            this.ProjectId = projectId;
            // to ensure "configurationIds" is required (not null)
            if (configurationIds == null)
            {
                throw new ArgumentNullException("configurationIds is a required property for CreateTestRunAndFillByAutoTestCasesApiModel and cannot be null");
            }
            this.ConfigurationIds = configurationIds;
            // to ensure "option" is required (not null)
            if (option == null)
            {
                throw new ArgumentNullException("option is a required property for CreateTestRunAndFillByAutoTestCasesApiModel and cannot be null");
            }
            this.Option = option;
            this.Filter = filter;
            this.Name = name;
            this.Description = description;
            this.LaunchSource = launchSource;
            this.Tags = tags;
        }

        /// <summary>
        /// Specifies the GUID of the project, in which a test run will be created.
        /// </summary>
        /// <value>Specifies the GUID of the project, in which a test run will be created.</value>
        [DataMember(Name = "projectId", IsRequired = true, EmitDefaultValue = true)]
        public Guid ProjectId { get; set; }

        /// <summary>
        /// Specifies the filter for selecting autotests, from which test points are created.
        /// </summary>
        /// <value>Specifies the filter for selecting autotests, from which test points are created.</value>
        [DataMember(Name = "filter", EmitDefaultValue = true)]
        public CompositeFilter Filter { get; set; }

        /// <summary>
        /// Specifies the name of the test run.
        /// </summary>
        /// <value>Specifies the name of the test run.</value>
        [DataMember(Name = "name", EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Specifies the configuration GUIDs, from which test points are created. You can specify several GUIDs.
        /// </summary>
        /// <value>Specifies the configuration GUIDs, from which test points are created. You can specify several GUIDs.</value>
        [DataMember(Name = "configurationIds", IsRequired = true, EmitDefaultValue = true)]
        public List<Guid> ConfigurationIds { get; set; }

        /// <summary>
        /// Specifies the test run description.
        /// </summary>
        /// <value>Specifies the test run description.</value>
        [DataMember(Name = "description", EmitDefaultValue = true)]
        public string Description { get; set; }

        /// <summary>
        /// Specifies the test run launch source.
        /// </summary>
        /// <value>Specifies the test run launch source.</value>
        [DataMember(Name = "launchSource", EmitDefaultValue = true)]
        public string LaunchSource { get; set; }

        /// <summary>
        /// Specifies the test run launch options.
        /// </summary>
        /// <value>Specifies the test run launch options.</value>
        [DataMember(Name = "option", IsRequired = true, EmitDefaultValue = true)]
        public TestRunLaunchOptionApiModel Option { get; set; }

        /// <summary>
        /// Collection of tags to assign to the test run
        /// </summary>
        /// <value>Collection of tags to assign to the test run</value>
        [DataMember(Name = "tags", EmitDefaultValue = true)]
        public List<string> Tags { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateTestRunAndFillByAutoTestCasesApiModel {\n");
            sb.Append("  ProjectId: ").Append(ProjectId).Append("\n");
            sb.Append("  Filter: ").Append(Filter).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  ConfigurationIds: ").Append(ConfigurationIds).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  LaunchSource: ").Append(LaunchSource).Append("\n");
            sb.Append("  Option: ").Append(Option).Append("\n");
            sb.Append("  Tags: ").Append(Tags).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
