/*
 * API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = TestIT.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = TestIT.ApiClient.Client.OpenAPIDateConverter;

namespace TestIT.ApiClient.Model
{
    /// <summary>
    /// ExternalIssueApiResult
    /// </summary>
    [DataContract(Name = "ExternalIssueApiResult")]
    public partial class ExternalIssueApiResult : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ExternalIssueApiResult" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ExternalIssueApiResult() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ExternalIssueApiResult" /> class.
        /// </summary>
        /// <param name="id">Identiief of external issue (required).</param>
        /// <param name="externalId">Identifier of external issue in external service (required).</param>
        /// <param name="url">Url of external issue (required).</param>
        /// <param name="metadata">Metadata of external issue from external service (required).</param>
        public ExternalIssueApiResult(Guid id = default(Guid), string externalId = default(string), string url = default(string), ExternalIssueApiMetadata metadata = default(ExternalIssueApiMetadata))
        {
            this.Id = id;
            // to ensure "externalId" is required (not null)
            if (externalId == null)
            {
                throw new ArgumentNullException("externalId is a required property for ExternalIssueApiResult and cannot be null");
            }
            this.ExternalId = externalId;
            // to ensure "url" is required (not null)
            if (url == null)
            {
                throw new ArgumentNullException("url is a required property for ExternalIssueApiResult and cannot be null");
            }
            this.Url = url;
            // to ensure "metadata" is required (not null)
            if (metadata == null)
            {
                throw new ArgumentNullException("metadata is a required property for ExternalIssueApiResult and cannot be null");
            }
            this.Metadata = metadata;
        }

        /// <summary>
        /// Identiief of external issue
        /// </summary>
        /// <value>Identiief of external issue</value>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public Guid Id { get; set; }

        /// <summary>
        /// Identifier of external issue in external service
        /// </summary>
        /// <value>Identifier of external issue in external service</value>
        [DataMember(Name = "externalId", IsRequired = true, EmitDefaultValue = true)]
        public string ExternalId { get; set; }

        /// <summary>
        /// Url of external issue
        /// </summary>
        /// <value>Url of external issue</value>
        [DataMember(Name = "url", IsRequired = true, EmitDefaultValue = true)]
        public string Url { get; set; }

        /// <summary>
        /// Metadata of external issue from external service
        /// </summary>
        /// <value>Metadata of external issue from external service</value>
        [DataMember(Name = "metadata", IsRequired = true, EmitDefaultValue = true)]
        public ExternalIssueApiMetadata Metadata { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ExternalIssueApiResult {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  ExternalId: ").Append(ExternalId).Append("\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("  Metadata: ").Append(Metadata).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
