/*
 * API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = TestIT.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = TestIT.ApiClient.Client.OpenAPIDateConverter;

namespace TestIT.ApiClient.Model
{
    /// <summary>
    /// Defines FailureCategory
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum FailureCategory
    {
        /// <summary>
        /// Enum InfrastructureDefect for value: InfrastructureDefect
        /// </summary>
        [EnumMember(Value = "InfrastructureDefect")]
        InfrastructureDefect = 1,

        /// <summary>
        /// Enum ProductDefect for value: ProductDefect
        /// </summary>
        [EnumMember(Value = "ProductDefect")]
        ProductDefect = 2,

        /// <summary>
        /// Enum TestDefect for value: TestDefect
        /// </summary>
        [EnumMember(Value = "TestDefect")]
        TestDefect = 3,

        /// <summary>
        /// Enum NoDefect for value: NoDefect
        /// </summary>
        [EnumMember(Value = "NoDefect")]
        NoDefect = 4,

        /// <summary>
        /// Enum NoAnalytics for value: NoAnalytics
        /// </summary>
        [EnumMember(Value = "NoAnalytics")]
        NoAnalytics = 5

    }

}
