/*
 * API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = TestIT.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = TestIT.ApiClient.Client.OpenAPIDateConverter;

namespace TestIT.ApiClient.Model
{
    /// <summary>
    /// FailureClassRegexApiResult
    /// </summary>
    [DataContract(Name = "FailureClassRegexApiResult")]
    public partial class FailureClassRegexApiResult : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FailureClassRegexApiResult" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected FailureClassRegexApiResult() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="FailureClassRegexApiResult" /> class.
        /// </summary>
        /// <param name="id">Regex unique identifier (required).</param>
        /// <param name="isDeleted">Indicates if the entity is deleted (required).</param>
        /// <param name="regexText">Regex value (required).</param>
        /// <param name="failureClassId">Failure category identifier (required).</param>
        public FailureClassRegexApiResult(Guid id = default(Guid), bool isDeleted = default(bool), string regexText = default(string), Guid failureClassId = default(Guid))
        {
            this.Id = id;
            this.IsDeleted = isDeleted;
            // to ensure "regexText" is required (not null)
            if (regexText == null)
            {
                throw new ArgumentNullException("regexText is a required property for FailureClassRegexApiResult and cannot be null");
            }
            this.RegexText = regexText;
            this.FailureClassId = failureClassId;
        }

        /// <summary>
        /// Regex unique identifier
        /// </summary>
        /// <value>Regex unique identifier</value>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public Guid Id { get; set; }

        /// <summary>
        /// Indicates if the entity is deleted
        /// </summary>
        /// <value>Indicates if the entity is deleted</value>
        [DataMember(Name = "isDeleted", IsRequired = true, EmitDefaultValue = true)]
        public bool IsDeleted { get; set; }

        /// <summary>
        /// Regex value
        /// </summary>
        /// <value>Regex value</value>
        [DataMember(Name = "regexText", IsRequired = true, EmitDefaultValue = true)]
        public string RegexText { get; set; }

        /// <summary>
        /// Failure category identifier
        /// </summary>
        /// <value>Failure category identifier</value>
        [DataMember(Name = "failureClassId", IsRequired = true, EmitDefaultValue = true)]
        public Guid FailureClassId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class FailureClassRegexApiResult {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  IsDeleted: ").Append(IsDeleted).Append("\n");
            sb.Append("  RegexText: ").Append(RegexText).Append("\n");
            sb.Append("  FailureClassId: ").Append(FailureClassId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
