/*
 * API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = TestIT.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = TestIT.ApiClient.Client.OpenAPIDateConverter;

namespace TestIT.ApiClient.Model
{
    /// <summary>
    /// GetExternalFormApiResult
    /// </summary>
    [DataContract(Name = "GetExternalFormApiResult")]
    public partial class GetExternalFormApiResult : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetExternalFormApiResult" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GetExternalFormApiResult() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetExternalFormApiResult" /> class.
        /// </summary>
        /// <param name="testResultIds">Linked test result IDs (required).</param>
        /// <param name="form">External form definition (required).</param>
        public GetExternalFormApiResult(List<Guid> testResultIds = default, ExternalFormModel form = default)
        {
            // to ensure "testResultIds" is required (not null)
            if (testResultIds == null)
            {
                throw new ArgumentNullException("testResultIds is a required property for GetExternalFormApiResult and cannot be null");
            }
            this.TestResultIds = testResultIds;
            // to ensure "form" is required (not null)
            if (form == null)
            {
                throw new ArgumentNullException("form is a required property for GetExternalFormApiResult and cannot be null");
            }
            this.Form = form;
        }

        /// <summary>
        /// Linked test result IDs
        /// </summary>
        /// <value>Linked test result IDs</value>
        [DataMember(Name = "testResultIds", IsRequired = true, EmitDefaultValue = true)]
        public List<Guid> TestResultIds { get; set; }

        /// <summary>
        /// External form definition
        /// </summary>
        /// <value>External form definition</value>
        [DataMember(Name = "form", IsRequired = true, EmitDefaultValue = true)]
        public ExternalFormModel Form { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetExternalFormApiResult {\n");
            sb.Append("  TestResultIds: ").Append(TestResultIds).Append("\n");
            sb.Append("  Form: ").Append(Form).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
