/*
 * API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = TestIT.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = TestIT.ApiClient.Client.OpenAPIDateConverter;

namespace TestIT.ApiClient.Model
{
    /// <summary>
    /// ProjectExternalServiceApiResult
    /// </summary>
    [DataContract(Name = "ProjectExternalServiceApiResult")]
    public partial class ProjectExternalServiceApiResult : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ProjectExternalServiceApiResult" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ProjectExternalServiceApiResult() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ProjectExternalServiceApiResult" /> class.
        /// </summary>
        /// <param name="id">The unique ID of the external service (required).</param>
        /// <param name="name">The name of the external service (required).</param>
        /// <param name="metadata">The metadata associated with the external service (required).</param>
        /// <param name="enabled">Indicates whether the external service is enabled or not (required).</param>
        public ProjectExternalServiceApiResult(Guid id = default, string name = default, ExternalServiceMetadataApiResult metadata = default, bool enabled = default)
        {
            this.Id = id;
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for ProjectExternalServiceApiResult and cannot be null");
            }
            this.Name = name;
            // to ensure "metadata" is required (not null)
            if (metadata == null)
            {
                throw new ArgumentNullException("metadata is a required property for ProjectExternalServiceApiResult and cannot be null");
            }
            this.Metadata = metadata;
            this.Enabled = enabled;
        }

        /// <summary>
        /// The unique ID of the external service
        /// </summary>
        /// <value>The unique ID of the external service</value>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public Guid Id { get; set; }

        /// <summary>
        /// The name of the external service
        /// </summary>
        /// <value>The name of the external service</value>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// The metadata associated with the external service
        /// </summary>
        /// <value>The metadata associated with the external service</value>
        [DataMember(Name = "metadata", IsRequired = true, EmitDefaultValue = true)]
        public ExternalServiceMetadataApiResult Metadata { get; set; }

        /// <summary>
        /// Indicates whether the external service is enabled or not
        /// </summary>
        /// <value>Indicates whether the external service is enabled or not</value>
        [DataMember(Name = "enabled", IsRequired = true, EmitDefaultValue = true)]
        public bool Enabled { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ProjectExternalServiceApiResult {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Metadata: ").Append(Metadata).Append("\n");
            sb.Append("  Enabled: ").Append(Enabled).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
