/*
 * API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = TestIT.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = TestIT.ApiClient.Client.OpenAPIDateConverter;

namespace TestIT.ApiClient.Model
{
    /// <summary>
    /// ProjectFailureCategoryGroupItemApiResult
    /// </summary>
    [DataContract(Name = "ProjectFailureCategoryGroupItemApiResult")]
    public partial class ProjectFailureCategoryGroupItemApiResult : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ProjectFailureCategoryGroupItemApiResult" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ProjectFailureCategoryGroupItemApiResult() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ProjectFailureCategoryGroupItemApiResult" /> class.
        /// </summary>
        /// <param name="group">Group details.</param>
        /// <param name="items">Group data (required).</param>
        public ProjectFailureCategoryGroupItemApiResult(FailureCategoryGroupApiResult group = default, List<ProjectFailureCategoryApiResult> items = default)
        {
            // to ensure "items" is required (not null)
            if (items == null)
            {
                throw new ArgumentNullException("items is a required property for ProjectFailureCategoryGroupItemApiResult and cannot be null");
            }
            this.Items = items;
            this.Group = group;
        }

        /// <summary>
        /// Group details
        /// </summary>
        /// <value>Group details</value>
        [DataMember(Name = "group", EmitDefaultValue = true)]
        public FailureCategoryGroupApiResult Group { get; set; }

        /// <summary>
        /// Group data
        /// </summary>
        /// <value>Group data</value>
        [DataMember(Name = "items", IsRequired = true, EmitDefaultValue = true)]
        public List<ProjectFailureCategoryApiResult> Items { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ProjectFailureCategoryGroupItemApiResult {\n");
            sb.Append("  Group: ").Append(Group).Append("\n");
            sb.Append("  Items: ").Append(Items).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
