/*
 * API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = TestIT.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = TestIT.ApiClient.Client.OpenAPIDateConverter;

namespace TestIT.ApiClient.Model
{
    /// <summary>
    /// TestResultFailureClassApiResult
    /// </summary>
    [DataContract(Name = "TestResultFailureClassApiResult")]
    public partial class TestResultFailureClassApiResult : IValidatableObject
    {

        /// <summary>
        /// Gets or Sets FailureCategory
        /// </summary>
        [DataMember(Name = "failureCategory", IsRequired = true, EmitDefaultValue = true)]
        public FailureCategory FailureCategory { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="TestResultFailureClassApiResult" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TestResultFailureClassApiResult() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TestResultFailureClassApiResult" /> class.
        /// </summary>
        /// <param name="failureCategory">failureCategory (required).</param>
        public TestResultFailureClassApiResult(FailureCategory failureCategory = default)
        {
            this.FailureCategory = failureCategory;
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TestResultFailureClassApiResult {\n");
            sb.Append("  FailureCategory: ").Append(FailureCategory).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
