/*
 * API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = TestIT.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = TestIT.ApiClient.Client.OpenAPIDateConverter;

namespace TestIT.ApiClient.Model
{
    /// <summary>
    /// TestPlanGroupByStatusType
    /// </summary>
    [DataContract(Name = "TestPlanGroupByStatusType")]
    public partial class TestPlanGroupByStatusType : IValidatableObject
    {

        /// <summary>
        /// Gets or Sets StatusType
        /// </summary>
        [DataMember(Name = "statusType", IsRequired = true, EmitDefaultValue = true)]
        public TestStatusType StatusType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="TestPlanGroupByStatusType" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TestPlanGroupByStatusType() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TestPlanGroupByStatusType" /> class.
        /// </summary>
        /// <param name="statusType">statusType (required).</param>
        /// <param name="value">value (required).</param>
        public TestPlanGroupByStatusType(TestStatusType statusType = default, long value = default)
        {
            this.StatusType = statusType;
            this.Value = value;
        }

        /// <summary>
        /// Gets or Sets Value
        /// </summary>
        [DataMember(Name = "value", IsRequired = true, EmitDefaultValue = true)]
        public long Value { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TestPlanGroupByStatusType {\n");
            sb.Append("  StatusType: ").Append(StatusType).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
