/*
 * API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = TestIT.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = TestIT.ApiClient.Client.OpenAPIDateConverter;

namespace TestIT.ApiClient.Model
{
    /// <summary>
    /// WorkItemExternalMetadataFieldFilterApiModel
    /// </summary>
    [DataContract(Name = "WorkItemExternalMetadataFieldFilterApiModel")]
    public partial class WorkItemExternalMetadataFieldFilterApiModel : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WorkItemExternalMetadataFieldFilterApiModel" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected WorkItemExternalMetadataFieldFilterApiModel() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="WorkItemExternalMetadataFieldFilterApiModel" /> class.
        /// </summary>
        /// <param name="value">Value of the field (required).</param>
        /// <param name="externalServiceId">Identifier of external service which is source of this value (required).</param>
        public WorkItemExternalMetadataFieldFilterApiModel(string value = default, Guid externalServiceId = default)
        {
            // to ensure "value" is required (not null)
            if (value == null)
            {
                throw new ArgumentNullException("value is a required property for WorkItemExternalMetadataFieldFilterApiModel and cannot be null");
            }
            this.Value = value;
            this.ExternalServiceId = externalServiceId;
        }

        /// <summary>
        /// Value of the field
        /// </summary>
        /// <value>Value of the field</value>
        [DataMember(Name = "value", IsRequired = true, EmitDefaultValue = true)]
        public string Value { get; set; }

        /// <summary>
        /// Identifier of external service which is source of this value
        /// </summary>
        /// <value>Identifier of external service which is source of this value</value>
        [DataMember(Name = "externalServiceId", IsRequired = true, EmitDefaultValue = true)]
        public Guid ExternalServiceId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class WorkItemExternalMetadataFieldFilterApiModel {\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("  ExternalServiceId: ").Append(ExternalServiceId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
