/*
 * API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TestIT.ApiClient.Model;
using TestIT.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TestIT.ApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing ApiV2TestRunsIdStatisticsFilterPostRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ApiV2TestRunsIdStatisticsFilterPostRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ApiV2TestRunsIdStatisticsFilterPostRequest
        //private ApiV2TestRunsIdStatisticsFilterPostRequest instance;

        public ApiV2TestRunsIdStatisticsFilterPostRequestTests()
        {
            // TODO uncomment below to create an instance of ApiV2TestRunsIdStatisticsFilterPostRequest
            //instance = new ApiV2TestRunsIdStatisticsFilterPostRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ApiV2TestRunsIdStatisticsFilterPostRequest
        /// </summary>
        [Fact]
        public void ApiV2TestRunsIdStatisticsFilterPostRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" ApiV2TestRunsIdStatisticsFilterPostRequest
            //Assert.IsType<ApiV2TestRunsIdStatisticsFilterPostRequest>(instance);
        }


        /// <summary>
        /// Test the property 'ConfigurationIds'
        /// </summary>
        [Fact]
        public void ConfigurationIdsTest()
        {
            // TODO unit test for the property 'ConfigurationIds'
        }
        /// <summary>
        /// Test the property 'Outcomes'
        /// </summary>
        [Fact]
        public void OutcomesTest()
        {
            // TODO unit test for the property 'Outcomes'
        }
        /// <summary>
        /// Test the property 'FailureCategories'
        /// </summary>
        [Fact]
        public void FailureCategoriesTest()
        {
            // TODO unit test for the property 'FailureCategories'
        }
        /// <summary>
        /// Test the property 'Namespace'
        /// </summary>
        [Fact]
        public void NamespaceTest()
        {
            // TODO unit test for the property 'Namespace'
        }
        /// <summary>
        /// Test the property 'ClassName'
        /// </summary>
        [Fact]
        public void ClassNameTest()
        {
            // TODO unit test for the property 'ClassName'
        }

    }

}
