/*
 * API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TestIT.ApiClient.Model;
using TestIT.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TestIT.ApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing ApiV2ConfigurationsSearchPostRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ApiV2ConfigurationsSearchPostRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ApiV2ConfigurationsSearchPostRequest
        //private ApiV2ConfigurationsSearchPostRequest instance;

        public ApiV2ConfigurationsSearchPostRequestTests()
        {
            // TODO uncomment below to create an instance of ApiV2ConfigurationsSearchPostRequest
            //instance = new ApiV2ConfigurationsSearchPostRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ApiV2ConfigurationsSearchPostRequest
        /// </summary>
        [Fact]
        public void ApiV2ConfigurationsSearchPostRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" ApiV2ConfigurationsSearchPostRequest
            //Assert.IsType<ApiV2ConfigurationsSearchPostRequest>(instance);
        }


        /// <summary>
        /// Test the property 'ProjectIds'
        /// </summary>
        [Fact]
        public void ProjectIdsTest()
        {
            // TODO unit test for the property 'ProjectIds'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'IsDeleted'
        /// </summary>
        [Fact]
        public void IsDeletedTest()
        {
            // TODO unit test for the property 'IsDeleted'
        }
        /// <summary>
        /// Test the property 'GlobalIds'
        /// </summary>
        [Fact]
        public void GlobalIdsTest()
        {
            // TODO unit test for the property 'GlobalIds'
        }

    }

}
