/*
 * API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TestIT.ApiClient.Model;
using TestIT.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TestIT.ApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing ApiV2TestPointsSearchPostRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ApiV2TestPointsSearchPostRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ApiV2TestPointsSearchPostRequest
        //private ApiV2TestPointsSearchPostRequest instance;

        public ApiV2TestPointsSearchPostRequestTests()
        {
            // TODO uncomment below to create an instance of ApiV2TestPointsSearchPostRequest
            //instance = new ApiV2TestPointsSearchPostRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ApiV2TestPointsSearchPostRequest
        /// </summary>
        [Fact]
        public void ApiV2TestPointsSearchPostRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" ApiV2TestPointsSearchPostRequest
            //Assert.IsType<ApiV2TestPointsSearchPostRequest>(instance);
        }


        /// <summary>
        /// Test the property 'TestPlanIds'
        /// </summary>
        [Fact]
        public void TestPlanIdsTest()
        {
            // TODO unit test for the property 'TestPlanIds'
        }
        /// <summary>
        /// Test the property 'TestSuiteIds'
        /// </summary>
        [Fact]
        public void TestSuiteIdsTest()
        {
            // TODO unit test for the property 'TestSuiteIds'
        }
        /// <summary>
        /// Test the property 'WorkItemGlobalIds'
        /// </summary>
        [Fact]
        public void WorkItemGlobalIdsTest()
        {
            // TODO unit test for the property 'WorkItemGlobalIds'
        }
        /// <summary>
        /// Test the property 'WorkItemMedianDuration'
        /// </summary>
        [Fact]
        public void WorkItemMedianDurationTest()
        {
            // TODO unit test for the property 'WorkItemMedianDuration'
        }
        /// <summary>
        /// Test the property 'WorkItemIsDeleted'
        /// </summary>
        [Fact]
        public void WorkItemIsDeletedTest()
        {
            // TODO unit test for the property 'WorkItemIsDeleted'
        }
        /// <summary>
        /// Test the property 'Statuses'
        /// </summary>
        [Fact]
        public void StatusesTest()
        {
            // TODO unit test for the property 'Statuses'
        }
        /// <summary>
        /// Test the property 'Priorities'
        /// </summary>
        [Fact]
        public void PrioritiesTest()
        {
            // TODO unit test for the property 'Priorities'
        }
        /// <summary>
        /// Test the property 'IsAutomated'
        /// </summary>
        [Fact]
        public void IsAutomatedTest()
        {
            // TODO unit test for the property 'IsAutomated'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'ConfigurationIds'
        /// </summary>
        [Fact]
        public void ConfigurationIdsTest()
        {
            // TODO unit test for the property 'ConfigurationIds'
        }
        /// <summary>
        /// Test the property 'TesterIds'
        /// </summary>
        [Fact]
        public void TesterIdsTest()
        {
            // TODO unit test for the property 'TesterIds'
        }
        /// <summary>
        /// Test the property 'Duration'
        /// </summary>
        [Fact]
        public void DurationTest()
        {
            // TODO unit test for the property 'Duration'
        }
        /// <summary>
        /// Test the property 'SectionIds'
        /// </summary>
        [Fact]
        public void SectionIdsTest()
        {
            // TODO unit test for the property 'SectionIds'
        }
        /// <summary>
        /// Test the property 'CreatedDate'
        /// </summary>
        [Fact]
        public void CreatedDateTest()
        {
            // TODO unit test for the property 'CreatedDate'
        }
        /// <summary>
        /// Test the property 'CreatedByIds'
        /// </summary>
        [Fact]
        public void CreatedByIdsTest()
        {
            // TODO unit test for the property 'CreatedByIds'
        }
        /// <summary>
        /// Test the property 'ModifiedDate'
        /// </summary>
        [Fact]
        public void ModifiedDateTest()
        {
            // TODO unit test for the property 'ModifiedDate'
        }
        /// <summary>
        /// Test the property 'ModifiedByIds'
        /// </summary>
        [Fact]
        public void ModifiedByIdsTest()
        {
            // TODO unit test for the property 'ModifiedByIds'
        }
        /// <summary>
        /// Test the property 'Tags'
        /// </summary>
        [Fact]
        public void TagsTest()
        {
            // TODO unit test for the property 'Tags'
        }
        /// <summary>
        /// Test the property 'Attributes'
        /// </summary>
        [Fact]
        public void AttributesTest()
        {
            // TODO unit test for the property 'Attributes'
        }
        /// <summary>
        /// Test the property 'WorkItemCreatedDate'
        /// </summary>
        [Fact]
        public void WorkItemCreatedDateTest()
        {
            // TODO unit test for the property 'WorkItemCreatedDate'
        }
        /// <summary>
        /// Test the property 'WorkItemCreatedByIds'
        /// </summary>
        [Fact]
        public void WorkItemCreatedByIdsTest()
        {
            // TODO unit test for the property 'WorkItemCreatedByIds'
        }
        /// <summary>
        /// Test the property 'WorkItemModifiedDate'
        /// </summary>
        [Fact]
        public void WorkItemModifiedDateTest()
        {
            // TODO unit test for the property 'WorkItemModifiedDate'
        }
        /// <summary>
        /// Test the property 'WorkItemModifiedByIds'
        /// </summary>
        [Fact]
        public void WorkItemModifiedByIdsTest()
        {
            // TODO unit test for the property 'WorkItemModifiedByIds'
        }

    }

}
