/*
 * API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TestIT.ApiClient.Model;
using TestIT.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TestIT.ApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing AttachmentModelAutoTestStepResultsModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AttachmentModelAutoTestStepResultsModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AttachmentModelAutoTestStepResultsModel
        //private AttachmentModelAutoTestStepResultsModel instance;

        public AttachmentModelAutoTestStepResultsModelTests()
        {
            // TODO uncomment below to create an instance of AttachmentModelAutoTestStepResultsModel
            //instance = new AttachmentModelAutoTestStepResultsModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AttachmentModelAutoTestStepResultsModel
        /// </summary>
        [Fact]
        public void AttachmentModelAutoTestStepResultsModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" AttachmentModelAutoTestStepResultsModel
            //Assert.IsType<AttachmentModelAutoTestStepResultsModel>(instance);
        }


        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Info'
        /// </summary>
        [Fact]
        public void InfoTest()
        {
            // TODO unit test for the property 'Info'
        }
        /// <summary>
        /// Test the property 'StartedOn'
        /// </summary>
        [Fact]
        public void StartedOnTest()
        {
            // TODO unit test for the property 'StartedOn'
        }
        /// <summary>
        /// Test the property 'CompletedOn'
        /// </summary>
        [Fact]
        public void CompletedOnTest()
        {
            // TODO unit test for the property 'CompletedOn'
        }
        /// <summary>
        /// Test the property 'Duration'
        /// </summary>
        [Fact]
        public void DurationTest()
        {
            // TODO unit test for the property 'Duration'
        }
        /// <summary>
        /// Test the property 'Outcome'
        /// </summary>
        [Fact]
        public void OutcomeTest()
        {
            // TODO unit test for the property 'Outcome'
        }
        /// <summary>
        /// Test the property 'StepResults'
        /// </summary>
        [Fact]
        public void StepResultsTest()
        {
            // TODO unit test for the property 'StepResults'
        }
        /// <summary>
        /// Test the property 'Attachments'
        /// </summary>
        [Fact]
        public void AttachmentsTest()
        {
            // TODO unit test for the property 'Attachments'
        }
        /// <summary>
        /// Test the property 'Parameters'
        /// </summary>
        [Fact]
        public void ParametersTest()
        {
            // TODO unit test for the property 'Parameters'
        }

    }

}
