/*
 * API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TestIT.ApiClient.Model;
using TestIT.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TestIT.ApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing MoveRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MoveRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MoveRequest
        //private MoveRequest instance;

        public MoveRequestTests()
        {
            // TODO uncomment below to create an instance of MoveRequest
            //instance = new MoveRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MoveRequest
        /// </summary>
        [Fact]
        public void MoveRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" MoveRequest
            //Assert.IsType<MoveRequest>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'OldParentId'
        /// </summary>
        [Fact]
        public void OldParentIdTest()
        {
            // TODO unit test for the property 'OldParentId'
        }
        /// <summary>
        /// Test the property 'ParentId'
        /// </summary>
        [Fact]
        public void ParentIdTest()
        {
            // TODO unit test for the property 'ParentId'
        }
        /// <summary>
        /// Test the property 'NextSectionId'
        /// </summary>
        [Fact]
        public void NextSectionIdTest()
        {
            // TODO unit test for the property 'NextSectionId'
        }

    }

}
