/*
 * API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TestIT.ApiClient.Model;
using TestIT.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TestIT.ApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing TagSelectModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TagSelectModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TagSelectModel
        //private TagSelectModel instance;

        public TagSelectModelTests()
        {
            // TODO uncomment below to create an instance of TagSelectModel
            //instance = new TagSelectModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TagSelectModel
        /// </summary>
        [Fact]
        public void TagSelectModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" TagSelectModel
            //Assert.IsType<TagSelectModel>(instance);
        }


        /// <summary>
        /// Test the property 'Filter'
        /// </summary>
        [Fact]
        public void FilterTest()
        {
            // TODO unit test for the property 'Filter'
        }
        /// <summary>
        /// Test the property 'ExtractionModel'
        /// </summary>
        [Fact]
        public void ExtractionModelTest()
        {
            // TODO unit test for the property 'ExtractionModel'
        }

    }

}
