/*
 * API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TestIT.ApiClient.Model;
using TestIT.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TestIT.ApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing TestPointsExtractionModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TestPointsExtractionModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TestPointsExtractionModel
        //private TestPointsExtractionModel instance;

        public TestPointsExtractionModelTests()
        {
            // TODO uncomment below to create an instance of TestPointsExtractionModel
            //instance = new TestPointsExtractionModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TestPointsExtractionModel
        /// </summary>
        [Fact]
        public void TestPointsExtractionModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" TestPointsExtractionModel
            //Assert.IsType<TestPointsExtractionModel>(instance);
        }


        /// <summary>
        /// Test the property 'Ids'
        /// </summary>
        [Fact]
        public void IdsTest()
        {
            // TODO unit test for the property 'Ids'
        }

    }

}
