/*
 * API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TestIT.ApiClient.Model;
using TestIT.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TestIT.ApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing TestPlanWithAnalyticModelAnalytic
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TestPlanWithAnalyticModelAnalyticTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TestPlanWithAnalyticModelAnalytic
        //private TestPlanWithAnalyticModelAnalytic instance;

        public TestPlanWithAnalyticModelAnalyticTests()
        {
            // TODO uncomment below to create an instance of TestPlanWithAnalyticModelAnalytic
            //instance = new TestPlanWithAnalyticModelAnalytic();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TestPlanWithAnalyticModelAnalytic
        /// </summary>
        [Fact]
        public void TestPlanWithAnalyticModelAnalyticInstanceTest()
        {
            // TODO uncomment below to test "IsType" TestPlanWithAnalyticModelAnalytic
            //Assert.IsType<TestPlanWithAnalyticModelAnalytic>(instance);
        }


        /// <summary>
        /// Test the property 'CountGroupByStatus'
        /// </summary>
        [Fact]
        public void CountGroupByStatusTest()
        {
            // TODO unit test for the property 'CountGroupByStatus'
        }
        /// <summary>
        /// Test the property 'SumGroupByTester'
        /// </summary>
        [Fact]
        public void SumGroupByTesterTest()
        {
            // TODO unit test for the property 'SumGroupByTester'
        }
        /// <summary>
        /// Test the property 'CountGroupByTester'
        /// </summary>
        [Fact]
        public void CountGroupByTesterTest()
        {
            // TODO unit test for the property 'CountGroupByTester'
        }
        /// <summary>
        /// Test the property 'CountGroupByTestSuite'
        /// </summary>
        [Fact]
        public void CountGroupByTestSuiteTest()
        {
            // TODO unit test for the property 'CountGroupByTestSuite'
        }
        /// <summary>
        /// Test the property 'CountGroupByTesterAndStatus'
        /// </summary>
        [Fact]
        public void CountGroupByTesterAndStatusTest()
        {
            // TODO unit test for the property 'CountGroupByTesterAndStatus'
        }

    }

}
