/*
 * API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TestIT.ApiClient.Model;
using TestIT.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TestIT.ApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing TestPointByTestSuiteModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TestPointByTestSuiteModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TestPointByTestSuiteModel
        //private TestPointByTestSuiteModel instance;

        public TestPointByTestSuiteModelTests()
        {
            // TODO uncomment below to create an instance of TestPointByTestSuiteModel
            //instance = new TestPointByTestSuiteModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TestPointByTestSuiteModel
        /// </summary>
        [Fact]
        public void TestPointByTestSuiteModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" TestPointByTestSuiteModel
            //Assert.IsType<TestPointByTestSuiteModel>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'TesterId'
        /// </summary>
        [Fact]
        public void TesterIdTest()
        {
            // TODO unit test for the property 'TesterId'
        }
        /// <summary>
        /// Test the property 'WorkItemId'
        /// </summary>
        [Fact]
        public void WorkItemIdTest()
        {
            // TODO unit test for the property 'WorkItemId'
        }
        /// <summary>
        /// Test the property 'ConfigurationId'
        /// </summary>
        [Fact]
        public void ConfigurationIdTest()
        {
            // TODO unit test for the property 'ConfigurationId'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'LastTestResultId'
        /// </summary>
        [Fact]
        public void LastTestResultIdTest()
        {
            // TODO unit test for the property 'LastTestResultId'
        }
        /// <summary>
        /// Test the property 'IterationId'
        /// </summary>
        [Fact]
        public void IterationIdTest()
        {
            // TODO unit test for the property 'IterationId'
        }
        /// <summary>
        /// Test the property 'WorkItemMedianDuration'
        /// </summary>
        [Fact]
        public void WorkItemMedianDurationTest()
        {
            // TODO unit test for the property 'WorkItemMedianDuration'
        }

    }

}
