/*
 * API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TestIT.ApiClient.Model;
using TestIT.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TestIT.ApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing TestRunExtractionModelIds
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TestRunExtractionModelIdsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TestRunExtractionModelIds
        //private TestRunExtractionModelIds instance;

        public TestRunExtractionModelIdsTests()
        {
            // TODO uncomment below to create an instance of TestRunExtractionModelIds
            //instance = new TestRunExtractionModelIds();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TestRunExtractionModelIds
        /// </summary>
        [Fact]
        public void TestRunExtractionModelIdsInstanceTest()
        {
            // TODO uncomment below to test "IsType" TestRunExtractionModelIds
            //Assert.IsType<TestRunExtractionModelIds>(instance);
        }


        /// <summary>
        /// Test the property 'Include'
        /// </summary>
        [Fact]
        public void IncludeTest()
        {
            // TODO unit test for the property 'Include'
        }
        /// <summary>
        /// Test the property 'Exclude'
        /// </summary>
        [Fact]
        public void ExcludeTest()
        {
            // TODO unit test for the property 'Exclude'
        }

    }

}
