/*
 * API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TestIT.ApiClient.Model;
using TestIT.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TestIT.ApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing TestResultShortGetModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TestResultShortGetModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TestResultShortGetModel
        //private TestResultShortGetModel instance;

        public TestResultShortGetModelTests()
        {
            // TODO uncomment below to create an instance of TestResultShortGetModel
            //instance = new TestResultShortGetModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TestResultShortGetModel
        /// </summary>
        [Fact]
        public void TestResultShortGetModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" TestResultShortGetModel
            //Assert.IsType<TestResultShortGetModel>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'AutotestGlobalId'
        /// </summary>
        [Fact]
        public void AutotestGlobalIdTest()
        {
            // TODO unit test for the property 'AutotestGlobalId'
        }
        /// <summary>
        /// Test the property 'TestRunId'
        /// </summary>
        [Fact]
        public void TestRunIdTest()
        {
            // TODO unit test for the property 'TestRunId'
        }
        /// <summary>
        /// Test the property 'ConfigurationId'
        /// </summary>
        [Fact]
        public void ConfigurationIdTest()
        {
            // TODO unit test for the property 'ConfigurationId'
        }
        /// <summary>
        /// Test the property 'ConfigurationName'
        /// </summary>
        [Fact]
        public void ConfigurationNameTest()
        {
            // TODO unit test for the property 'ConfigurationName'
        }
        /// <summary>
        /// Test the property 'Outcome'
        /// </summary>
        [Fact]
        public void OutcomeTest()
        {
            // TODO unit test for the property 'Outcome'
        }
        /// <summary>
        /// Test the property 'ResultReasons'
        /// </summary>
        [Fact]
        public void ResultReasonsTest()
        {
            // TODO unit test for the property 'ResultReasons'
        }
        /// <summary>
        /// Test the property 'Comment'
        /// </summary>
        [Fact]
        public void CommentTest()
        {
            // TODO unit test for the property 'Comment'
        }
        /// <summary>
        /// Test the property 'Date'
        /// </summary>
        [Fact]
        public void DateTest()
        {
            // TODO unit test for the property 'Date'
        }
        /// <summary>
        /// Test the property 'Duration'
        /// </summary>
        [Fact]
        public void DurationTest()
        {
            // TODO unit test for the property 'Duration'
        }
        /// <summary>
        /// Test the property 'Links'
        /// </summary>
        [Fact]
        public void LinksTest()
        {
            // TODO unit test for the property 'Links'
        }
        /// <summary>
        /// Test the property 'Attachments'
        /// </summary>
        [Fact]
        public void AttachmentsTest()
        {
            // TODO unit test for the property 'Attachments'
        }

    }

}
