/*
 * API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TestIT.ApiClient.Model;
using TestIT.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TestIT.ApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing TestSuiteV2PutModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TestSuiteV2PutModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TestSuiteV2PutModel
        //private TestSuiteV2PutModel instance;

        public TestSuiteV2PutModelTests()
        {
            // TODO uncomment below to create an instance of TestSuiteV2PutModel
            //instance = new TestSuiteV2PutModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TestSuiteV2PutModel
        /// </summary>
        [Fact]
        public void TestSuiteV2PutModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" TestSuiteV2PutModel
            //Assert.IsType<TestSuiteV2PutModel>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'ParentId'
        /// </summary>
        [Fact]
        public void ParentIdTest()
        {
            // TODO unit test for the property 'ParentId'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'IsDeleted'
        /// </summary>
        [Fact]
        public void IsDeletedTest()
        {
            // TODO unit test for the property 'IsDeleted'
        }
        /// <summary>
        /// Test the property 'AutoRefresh'
        /// </summary>
        [Fact]
        public void AutoRefreshTest()
        {
            // TODO unit test for the property 'AutoRefresh'
        }

    }

}
