/*
 * API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TestIT.ApiClient.Model;
using TestIT.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TestIT.ApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing TestRunTestResultsPartialBulkSetModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TestRunTestResultsPartialBulkSetModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TestRunTestResultsPartialBulkSetModel
        //private TestRunTestResultsPartialBulkSetModel instance;

        public TestRunTestResultsPartialBulkSetModelTests()
        {
            // TODO uncomment below to create an instance of TestRunTestResultsPartialBulkSetModel
            //instance = new TestRunTestResultsPartialBulkSetModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TestRunTestResultsPartialBulkSetModel
        /// </summary>
        [Fact]
        public void TestRunTestResultsPartialBulkSetModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" TestRunTestResultsPartialBulkSetModel
            //Assert.IsType<TestRunTestResultsPartialBulkSetModel>(instance);
        }


        /// <summary>
        /// Test the property 'Selector'
        /// </summary>
        [Fact]
        public void SelectorTest()
        {
            // TODO unit test for the property 'Selector'
        }
        /// <summary>
        /// Test the property 'ResultReasonIds'
        /// </summary>
        [Fact]
        public void ResultReasonIdsTest()
        {
            // TODO unit test for the property 'ResultReasonIds'
        }
        /// <summary>
        /// Test the property 'Links'
        /// </summary>
        [Fact]
        public void LinksTest()
        {
            // TODO unit test for the property 'Links'
        }
        /// <summary>
        /// Test the property 'Comment'
        /// </summary>
        [Fact]
        public void CommentTest()
        {
            // TODO unit test for the property 'Comment'
        }
        /// <summary>
        /// Test the property 'AttachmentIds'
        /// </summary>
        [Fact]
        public void AttachmentIdsTest()
        {
            // TODO unit test for the property 'AttachmentIds'
        }

    }

}
