/*
 * API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TestIT.ApiClient.Model;
using TestIT.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TestIT.ApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing TestPlanChangeModelTestPlanChangedFields
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TestPlanChangeModelTestPlanChangedFieldsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TestPlanChangeModelTestPlanChangedFields
        //private TestPlanChangeModelTestPlanChangedFields instance;

        public TestPlanChangeModelTestPlanChangedFieldsTests()
        {
            // TODO uncomment below to create an instance of TestPlanChangeModelTestPlanChangedFields
            //instance = new TestPlanChangeModelTestPlanChangedFields();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TestPlanChangeModelTestPlanChangedFields
        /// </summary>
        [Fact]
        public void TestPlanChangeModelTestPlanChangedFieldsInstanceTest()
        {
            // TODO uncomment below to test "IsType" TestPlanChangeModelTestPlanChangedFields
            //Assert.IsType<TestPlanChangeModelTestPlanChangedFields>(instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'ProductName'
        /// </summary>
        [Fact]
        public void ProductNameTest()
        {
            // TODO unit test for the property 'ProductName'
        }
        /// <summary>
        /// Test the property 'Build'
        /// </summary>
        [Fact]
        public void BuildTest()
        {
            // TODO unit test for the property 'Build'
        }
        /// <summary>
        /// Test the property 'Period'
        /// </summary>
        [Fact]
        public void PeriodTest()
        {
            // TODO unit test for the property 'Period'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Tags'
        /// </summary>
        [Fact]
        public void TagsTest()
        {
            // TODO unit test for the property 'Tags'
        }
        /// <summary>
        /// Test the property 'TestSuite'
        /// </summary>
        [Fact]
        public void TestSuiteTest()
        {
            // TODO unit test for the property 'TestSuite'
        }
        /// <summary>
        /// Test the property 'TestPoints'
        /// </summary>
        [Fact]
        public void TestPointsTest()
        {
            // TODO unit test for the property 'TestPoints'
        }
        /// <summary>
        /// Test the property 'TestResults'
        /// </summary>
        [Fact]
        public void TestResultsTest()
        {
            // TODO unit test for the property 'TestResults'
        }
        /// <summary>
        /// Test the property 'Locking'
        /// </summary>
        [Fact]
        public void LockingTest()
        {
            // TODO unit test for the property 'Locking'
        }
        /// <summary>
        /// Test the property 'HasAutomaticDurationTimer'
        /// </summary>
        [Fact]
        public void HasAutomaticDurationTimerTest()
        {
            // TODO unit test for the property 'HasAutomaticDurationTimer'
        }
        /// <summary>
        /// Test the property 'Attributes'
        /// </summary>
        [Fact]
        public void AttributesTest()
        {
            // TODO unit test for the property 'Attributes'
        }

    }

}
