/*
 * API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TestIT.ApiClient.Model;
using TestIT.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TestIT.ApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing WorkItemGroupGetModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WorkItemGroupGetModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WorkItemGroupGetModel
        //private WorkItemGroupGetModel instance;

        public WorkItemGroupGetModelTests()
        {
            // TODO uncomment below to create an instance of WorkItemGroupGetModel
            //instance = new WorkItemGroupGetModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WorkItemGroupGetModel
        /// </summary>
        [Fact]
        public void WorkItemGroupGetModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" WorkItemGroupGetModel
            //Assert.IsType<WorkItemGroupGetModel>(instance);
        }


        /// <summary>
        /// Test the property 'SelectModel'
        /// </summary>
        [Fact]
        public void SelectModelTest()
        {
            // TODO unit test for the property 'SelectModel'
        }
        /// <summary>
        /// Test the property 'GroupType'
        /// </summary>
        [Fact]
        public void GroupTypeTest()
        {
            // TODO unit test for the property 'GroupType'
        }
        /// <summary>
        /// Test the property 'CustomAttributeId'
        /// </summary>
        [Fact]
        public void CustomAttributeIdTest()
        {
            // TODO unit test for the property 'CustomAttributeId'
        }

    }

}
