/*
 * API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TestIT.ApiClient.Model;
using TestIT.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TestIT.ApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing WorkItemChangedFieldsViewModelState
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WorkItemChangedFieldsViewModelStateTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WorkItemChangedFieldsViewModelState
        //private WorkItemChangedFieldsViewModelState instance;

        public WorkItemChangedFieldsViewModelStateTests()
        {
            // TODO uncomment below to create an instance of WorkItemChangedFieldsViewModelState
            //instance = new WorkItemChangedFieldsViewModelState();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WorkItemChangedFieldsViewModelState
        /// </summary>
        [Fact]
        public void WorkItemChangedFieldsViewModelStateInstanceTest()
        {
            // TODO uncomment below to test "IsType" WorkItemChangedFieldsViewModelState
            //Assert.IsType<WorkItemChangedFieldsViewModelState>(instance);
        }


        /// <summary>
        /// Test the property 'OldValue'
        /// </summary>
        [Fact]
        public void OldValueTest()
        {
            // TODO unit test for the property 'OldValue'
        }
        /// <summary>
        /// Test the property 'NewValue'
        /// </summary>
        [Fact]
        public void NewValueTest()
        {
            // TODO unit test for the property 'NewValue'
        }

    }

}
