/*
 * API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = TestIt.Client.Client.OpenAPIDateConverter;

namespace TestIt.Client.Model
{
    /// <summary>
    /// SharedStepReferenceModel
    /// </summary>
    [DataContract(Name = "SharedStepReferenceModel")]
    public partial class SharedStepReferenceModel : IEquatable<SharedStepReferenceModel>, IValidatableObject
    {

        /// <summary>
        /// Gets or Sets Priority
        /// </summary>
        [DataMember(Name = "priority", EmitDefaultValue = false)]
        public WorkItemPriorityModel? Priority { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="SharedStepReferenceModel" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="globalId">globalId.</param>
        /// <param name="name">name.</param>
        /// <param name="entityTypeName">entityTypeName.</param>
        /// <param name="hasThisSharedStepAsStep">hasThisSharedStepAsStep.</param>
        /// <param name="hasThisSharedStepAsPrecondition">hasThisSharedStepAsPrecondition.</param>
        /// <param name="hasThisSharedStepAsPostcondition">hasThisSharedStepAsPostcondition.</param>
        /// <param name="createdById">createdById.</param>
        /// <param name="modifiedById">modifiedById.</param>
        /// <param name="createdDate">createdDate.</param>
        /// <param name="modifiedDate">modifiedDate.</param>
        /// <param name="state">state.</param>
        /// <param name="priority">priority.</param>
        /// <param name="isDeleted">isDeleted.</param>
        /// <param name="versionId">used for versioning changes in workitem.</param>
        public SharedStepReferenceModel(Guid id = default(Guid), long globalId = default(long), string name = default(string), string entityTypeName = default(string), bool hasThisSharedStepAsStep = default(bool), bool hasThisSharedStepAsPrecondition = default(bool), bool hasThisSharedStepAsPostcondition = default(bool), Guid createdById = default(Guid), Guid? modifiedById = default(Guid?), DateTime? createdDate = default(DateTime?), DateTime? modifiedDate = default(DateTime?), string state = default(string), WorkItemPriorityModel? priority = default(WorkItemPriorityModel?), bool isDeleted = default(bool), Guid versionId = default(Guid))
        {
            this.Id = id;
            this.GlobalId = globalId;
            this.Name = name;
            this.EntityTypeName = entityTypeName;
            this.HasThisSharedStepAsStep = hasThisSharedStepAsStep;
            this.HasThisSharedStepAsPrecondition = hasThisSharedStepAsPrecondition;
            this.HasThisSharedStepAsPostcondition = hasThisSharedStepAsPostcondition;
            this.CreatedById = createdById;
            this.ModifiedById = modifiedById;
            this.CreatedDate = createdDate;
            this.ModifiedDate = modifiedDate;
            this.State = state;
            this.Priority = priority;
            this.IsDeleted = isDeleted;
            this.VersionId = versionId;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public Guid Id { get; set; }

        /// <summary>
        /// Gets or Sets GlobalId
        /// </summary>
        [DataMember(Name = "globalId", EmitDefaultValue = false)]
        public long GlobalId { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets EntityTypeName
        /// </summary>
        [DataMember(Name = "entityTypeName", EmitDefaultValue = true)]
        public string EntityTypeName { get; set; }

        /// <summary>
        /// Gets or Sets HasThisSharedStepAsStep
        /// </summary>
        [DataMember(Name = "hasThisSharedStepAsStep", EmitDefaultValue = true)]
        public bool HasThisSharedStepAsStep { get; set; }

        /// <summary>
        /// Gets or Sets HasThisSharedStepAsPrecondition
        /// </summary>
        [DataMember(Name = "hasThisSharedStepAsPrecondition", EmitDefaultValue = true)]
        public bool HasThisSharedStepAsPrecondition { get; set; }

        /// <summary>
        /// Gets or Sets HasThisSharedStepAsPostcondition
        /// </summary>
        [DataMember(Name = "hasThisSharedStepAsPostcondition", EmitDefaultValue = true)]
        public bool HasThisSharedStepAsPostcondition { get; set; }

        /// <summary>
        /// Gets or Sets CreatedById
        /// </summary>
        [DataMember(Name = "createdById", EmitDefaultValue = false)]
        public Guid CreatedById { get; set; }

        /// <summary>
        /// Gets or Sets ModifiedById
        /// </summary>
        [DataMember(Name = "modifiedById", EmitDefaultValue = true)]
        public Guid? ModifiedById { get; set; }

        /// <summary>
        /// Gets or Sets CreatedDate
        /// </summary>
        [DataMember(Name = "createdDate", EmitDefaultValue = true)]
        public DateTime? CreatedDate { get; set; }

        /// <summary>
        /// Gets or Sets ModifiedDate
        /// </summary>
        [DataMember(Name = "modifiedDate", EmitDefaultValue = true)]
        public DateTime? ModifiedDate { get; set; }

        /// <summary>
        /// Gets or Sets State
        /// </summary>
        [DataMember(Name = "state", EmitDefaultValue = true)]
        public string State { get; set; }

        /// <summary>
        /// Gets or Sets IsDeleted
        /// </summary>
        [DataMember(Name = "isDeleted", EmitDefaultValue = true)]
        public bool IsDeleted { get; set; }

        /// <summary>
        /// used for versioning changes in workitem
        /// </summary>
        /// <value>used for versioning changes in workitem</value>
        [DataMember(Name = "versionId", EmitDefaultValue = false)]
        public Guid VersionId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SharedStepReferenceModel {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  GlobalId: ").Append(GlobalId).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  EntityTypeName: ").Append(EntityTypeName).Append("\n");
            sb.Append("  HasThisSharedStepAsStep: ").Append(HasThisSharedStepAsStep).Append("\n");
            sb.Append("  HasThisSharedStepAsPrecondition: ").Append(HasThisSharedStepAsPrecondition).Append("\n");
            sb.Append("  HasThisSharedStepAsPostcondition: ").Append(HasThisSharedStepAsPostcondition).Append("\n");
            sb.Append("  CreatedById: ").Append(CreatedById).Append("\n");
            sb.Append("  ModifiedById: ").Append(ModifiedById).Append("\n");
            sb.Append("  CreatedDate: ").Append(CreatedDate).Append("\n");
            sb.Append("  ModifiedDate: ").Append(ModifiedDate).Append("\n");
            sb.Append("  State: ").Append(State).Append("\n");
            sb.Append("  Priority: ").Append(Priority).Append("\n");
            sb.Append("  IsDeleted: ").Append(IsDeleted).Append("\n");
            sb.Append("  VersionId: ").Append(VersionId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SharedStepReferenceModel);
        }

        /// <summary>
        /// Returns true if SharedStepReferenceModel instances are equal
        /// </summary>
        /// <param name="input">Instance of SharedStepReferenceModel to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SharedStepReferenceModel input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.GlobalId == input.GlobalId ||
                    this.GlobalId.Equals(input.GlobalId)
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.EntityTypeName == input.EntityTypeName ||
                    (this.EntityTypeName != null &&
                    this.EntityTypeName.Equals(input.EntityTypeName))
                ) && 
                (
                    this.HasThisSharedStepAsStep == input.HasThisSharedStepAsStep ||
                    this.HasThisSharedStepAsStep.Equals(input.HasThisSharedStepAsStep)
                ) && 
                (
                    this.HasThisSharedStepAsPrecondition == input.HasThisSharedStepAsPrecondition ||
                    this.HasThisSharedStepAsPrecondition.Equals(input.HasThisSharedStepAsPrecondition)
                ) && 
                (
                    this.HasThisSharedStepAsPostcondition == input.HasThisSharedStepAsPostcondition ||
                    this.HasThisSharedStepAsPostcondition.Equals(input.HasThisSharedStepAsPostcondition)
                ) && 
                (
                    this.CreatedById == input.CreatedById ||
                    (this.CreatedById != null &&
                    this.CreatedById.Equals(input.CreatedById))
                ) && 
                (
                    this.ModifiedById == input.ModifiedById ||
                    (this.ModifiedById != null &&
                    this.ModifiedById.Equals(input.ModifiedById))
                ) && 
                (
                    this.CreatedDate == input.CreatedDate ||
                    (this.CreatedDate != null &&
                    this.CreatedDate.Equals(input.CreatedDate))
                ) && 
                (
                    this.ModifiedDate == input.ModifiedDate ||
                    (this.ModifiedDate != null &&
                    this.ModifiedDate.Equals(input.ModifiedDate))
                ) && 
                (
                    this.State == input.State ||
                    (this.State != null &&
                    this.State.Equals(input.State))
                ) && 
                (
                    this.Priority == input.Priority ||
                    this.Priority.Equals(input.Priority)
                ) && 
                (
                    this.IsDeleted == input.IsDeleted ||
                    this.IsDeleted.Equals(input.IsDeleted)
                ) && 
                (
                    this.VersionId == input.VersionId ||
                    (this.VersionId != null &&
                    this.VersionId.Equals(input.VersionId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                {
                    hashCode = (hashCode * 59) + this.Id.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.GlobalId.GetHashCode();
                if (this.Name != null)
                {
                    hashCode = (hashCode * 59) + this.Name.GetHashCode();
                }
                if (this.EntityTypeName != null)
                {
                    hashCode = (hashCode * 59) + this.EntityTypeName.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.HasThisSharedStepAsStep.GetHashCode();
                hashCode = (hashCode * 59) + this.HasThisSharedStepAsPrecondition.GetHashCode();
                hashCode = (hashCode * 59) + this.HasThisSharedStepAsPostcondition.GetHashCode();
                if (this.CreatedById != null)
                {
                    hashCode = (hashCode * 59) + this.CreatedById.GetHashCode();
                }
                if (this.ModifiedById != null)
                {
                    hashCode = (hashCode * 59) + this.ModifiedById.GetHashCode();
                }
                if (this.CreatedDate != null)
                {
                    hashCode = (hashCode * 59) + this.CreatedDate.GetHashCode();
                }
                if (this.ModifiedDate != null)
                {
                    hashCode = (hashCode * 59) + this.ModifiedDate.GetHashCode();
                }
                if (this.State != null)
                {
                    hashCode = (hashCode * 59) + this.State.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.Priority.GetHashCode();
                hashCode = (hashCode * 59) + this.IsDeleted.GetHashCode();
                if (this.VersionId != null)
                {
                    hashCode = (hashCode * 59) + this.VersionId.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
