/*
 * API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = TestIt.Client.Client.OpenAPIDateConverter;

namespace TestIt.Client.Model
{
    /// <summary>
    /// Defines WidgetTypeModel
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum WidgetTypeModel
    {
        /// <summary>
        /// Enum LineChart for value: LineChart
        /// </summary>
        [EnumMember(Value = "LineChart")]
        LineChart = 1,

        /// <summary>
        /// Enum PieChart for value: PieChart
        /// </summary>
        [EnumMember(Value = "PieChart")]
        PieChart = 2,

        /// <summary>
        /// Enum HorizontalBarChart for value: HorizontalBarChart
        /// </summary>
        [EnumMember(Value = "HorizontalBarChart")]
        HorizontalBarChart = 3,

        /// <summary>
        /// Enum SectionTree for value: SectionTree
        /// </summary>
        [EnumMember(Value = "SectionTree")]
        SectionTree = 4,

        /// <summary>
        /// Enum UserRank for value: UserRank
        /// </summary>
        [EnumMember(Value = "UserRank")]
        UserRank = 5,

        /// <summary>
        /// Enum TimeLine for value: TimeLine
        /// </summary>
        [EnumMember(Value = "TimeLine")]
        TimeLine = 6

    }

}
