name: Publish

on:
  release:
    types:
      - created

env:
  PROJECT_DIR: ./src/TestIt.Api
  NUGET_DIR: ./nuget

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Restore dependencies
        run: dotnet restore ${{ env.PROJECT_DIR }}

      - name: Build
        run: |
          dotnet build --configuration Release \
          --no-restore ${{ env.PROJECT_DIR }}

      - name: Pack
        run: |
          dotnet pack --configuration Release \
          --no-build --output ${{ env.NUGET_DIR }} \
          ${{ env.PROJECT_DIR }}

      - name: Push
        run: |
          dotnet nuget push ${{ env.NUGET_DIR }}/*.nupkg \
          --source https://api.nuget.org/v3/index.json \
          --api-key ${{ secrets.NUGET_KEY }}
