name: Release

on:
  release:
    types:
      - created

env:
  PROJECT_DIR: ./src/TestIt.Api
  NUGET_DIR: ./nuget

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: NuGet-package
          path: ${{ env.NUGET_DIR }}

      - name: Publish to NuGet.org
        run: |
          dotnet nuget push ${{ env.NUGET_DIR }}/*.nupkg \
          --source https://api.nuget.org/v3/index.json \
          --api-key ${{ secrets.NUGET_KEY }}

      - name: Publish to GitHub Packages
        run: |
          dotnet nuget push ${{ env.NUGET_DIR }}/*.nupkg \
          --source https://nuget.pkg.github.com/testit-tms/index.json \
          --api-key ${{ secrets.GH_PACKAGES_KEY }}
