name: Validate

on:
  pull_request:
    branches: [master]
    paths:
      - "src/**"

  workflow_dispatch:

env:
  PROJECT_DIR: ./src/TestIt.Api
  VALIDATION: 1

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-deps: 0

      - name: Setup
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Restore dependencies
        run: dotnet restore ${{ env.PROJECT_DIR }}

      - name: Build
        run: dotnet build --no-restore ${{ env.PROJECT_DIR }}
